server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B9
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true #  显示SQL语句
        format_sql: true